# Generated by Django 6.0.5 on 2026-07-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_notification_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_ref',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='sale',
            name='sal_ref',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='supplier',
            name='sup_ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='reference',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
